[project]
name = "comfyui-cncc"
description = "ComfyUI ControlNet Control Center - save comfyui_controlnet_aux preprocessors as reusable presets and handle them from a single node"
version = "0.1.0"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/ketle-man/ComfyUI-CNCC"

[tool.comfy]
PublisherId = "statsu"
DisplayName = "ComfyUI-CNCC"
Icon = "https://raw.githubusercontent.com/ketle-man/ComfyUI-CNCC/master/docs/thumb.png"
